### ISSUE TITLE
Recent breaking changes

### ISSUE THREAD

**Issue by gtczap** [minus5/gofreetds#12]
Recent pull requests merged in to this repo have caused a regression.

Change 1: https://github.com/minus5/gofreetds/commit/dc2777a304d61b33486d77d39672d55aea3fb61e
Change 2: https://github.com/minus5/gofreetds/commit/b2a58917a6f72b09cf1f2fe8c79448673bc8bde6

Change 1 (@myself) was introduced to solve an issue with empty strings breaking the db. Change 2 (@thatguystone) was introduced 3 months later to solve the same issue. Both pull requests were then merged at the same time. Both changes address the same issue using different methods, but change 2 seems to have caused a regression in my code, causing errors in a codebase that was not erroring out before the change. Example error is included below. I apologize for not having better information to reproduce this at the moment. I actually like the way change 2 solved the issue better than change 1, and I'm not yet sure how change 2 is causing the issue, I just know that if I roll back to before it got pulled in then I no longer get this error.

Server Error: Msg 1001, Level 15 General SQL Server error: Check messages from the SQL Server Msg 137, Level 15 General SQL Server error: Check messages from the SQL Server Msg 1001, Level 15, State 1 Server 'LUR-SRV-01\SQLEXPRESS', Line 1 Line 1: Length or precision specification 0 is invalid. Msg 137, Level 15, State 2 Server 'LUR-SRV-01\SQLEXPRESS', Line 2 Must declare the scalar variable "@p1".

**Comment by thatguystone** [comment]
Could you paste in the Query/Statement/Exec that's causing the error?

**Comment by gtczap** [comment]
statement := `UPDATE device_list 
	SET location_id=?,
		property_id=?,
		site_id=?,
		name=?,
		external_device_id=?,
		disabled=?,
		device_type=?,
		ip_address=?,
		port=?,
		day_mode_override=?,
		args=?,
		config=?
	WHERE device_id=?`

	result, err := db.Exec(statement, device.LocationId, device.PropertyId, device.SiteId, device.Name, device.ExternalDeviceId, device.Disabled, device.DeviceType, device.IPAddress, device.Port, device.DayModeOverride, device.Args, device.Config, device.DeviceId)
	if err != nil {
		return nil, err
	}

**Comment by gtczap** [comment]
In the above db.Exec, device is a struct where LocationId and PropertyId are ints who's values are being set to 0. Actually I think we just found the issue.

**Comment by ianic** [comment]
Cold you please catch freetds log and post it here.
In the terminal run something like: 
```
 export TDSDUMP=/tmp/freetds.log
```
Then run the app in the same terminal. In /tmp/freetds.log find the line which looks like:
```
write.c:137:tds_put_string converting 383 bytes of "exec sp_executesql N'UPDATE device_list
```
after that is the actual query. It will be helpful to see the full query.

I tried to reproduce error but with no success. 
This is the test for which I hope to fail. It would be great if you could create failing test.

```go
func TestBugFixIssue11(t *testing.T) {
	runScripts(t, []string{
		`if exists(select * from sys.tables where name = 'device_list')
     drop table device_list`,

		`create table device_list (
       device_id int,
       site_id int,
       name varchar(255),
       config varchar(255) null,
       disabled bit )`,

		`insert into device_list (device_id, site_id, name, disabled, config) values (1, 1, 'name', 0, null)`,
	})

	device := &struct {
		DeviceId         int64          `db:"device_id" json:"id"`
		LocationId       int64          `db:"location_id" json:"locationId"`
		PropertyId       int64          `db:"property_id" json:"propertyId"`
		SiteId           int64          `db:"site_id" json:"siteId"`
		Name             string         `db:"name" json:"name"`
		ExternalDeviceId int64          `db:"external_device_id" json:"externalDeviceId"`
		Disabled         bool           `db:"disabled" json:"disabled"`
		DeviceType       int64          `db:"device_type" json:"sacDeviceType"`
		IPAddress        string         `db:"ip_address" json:"ipAddress"`
		Port             string         `db:"port" json:"port"`
		DayModeOverride  bool           `db:"day_mode_override" json:"dayModeOverride"`
		Args             string         `db:"args" json:"args"`
		Config           sql.NullString `db:"config" json:"config"`
	}{
		DeviceId: 1,
		Name:     "zdero",
		Disabled: false,
		SiteId:   123456789,
	}

	statement := `UPDATE device_list 
SET
    site_id=?,
    name=?,
    disabled=?,
    config=?
WHERE device_id=?`

	db, _ := open()
	result, err := db.Exec(statement, device.SiteId, device.Name, device.Disabled, device.Config, device.DeviceId)

	assert.Nil(t, err)
	assert.NotNil(t, result)
}
```

**Comment by gtczap** [comment]
write.c:140:tds_put_string converting 815 bytes of "exec sp_executesql N'UPDATE device_list 
		SET location_id=@p1,
			property_id=@p2,
			site_id=@p3,
			name=@p4,
			external_device_id=@p5,
			disabled=@p6,
			device_type=@p7,
			ip_address=@p8,
			port=@p9,
			day_mode_override=@p10,
			args=@p11,
			config=@p12
		WHERE device_id=@p13;
	   select cast(coalesce(scope_identity(), -1) as bigint) last_insert_id, 
	          cast(@@rowcount as bigint) rows_affected
	', N'@p1 bigint, @p2 bigint, @p3 bigint, @p4 nvarchar (12), @p5 bigint, @p6 nvarchar (5), @p7 bigint, @p8 nvarchar (0), @p9 nvarchar (0), @p10 nvarchar (5), @p11 nvarchar (77), @p12 nvarchar (5), @p13 bigint', @p1=0, @p2=0, @p3=9, @p4='Camera B-13A', @p5=8, @p6='false', @p7=3, @p8='', @p9='', @p10='false', @p11='{"group":"camera","type":"static","exacqId":1234567890,"xPos":123,"yPos":123}', @p12='<nil>', @p13=8"
	write.c:140:tds_put_string converting 687 bytes of "d=@p5,
			disabled=@p6,
			device_type=@p7,
			ip_address=@p8,
			port=@p9,
			day_mode_override=@p10,
			args=@p11,
			config=@p12
		WHERE device_id=@p13;
	   select cast(coalesce(scope_identity(), -1) as bigint) last_insert_id, 
	          cast(@@rowcount as bigint) rows_affected
	', N'@p1 bigint, @p2 bigint, @p3 bigint, @p4 nvarchar (12), @p5 bigint, @p6 nvarchar (5), @p7 bigint, @p8 nvarchar (0), @p9 nvarchar (0), @p10 nvarchar (5), @p11 nvarchar (77), @p12 nvarchar (5), @p13 bigint', @p1=0, @p2=0, @p3=9, @p4='Camera B-13A', @p5=8, @p6='false', @p7=3, @p8='', @p9='', @p10='false', @p11='{"group":"camera","type":"static","exacqId":1234567890,"xPos":123,"yPos":123}', @p12='<nil>', @p13=8"
	write.c:140:tds_put_string converting 559 bytes of "ERE device_id=@p13;
	   select cast(coalesce(scope_identity(), -1) as bigint) last_insert_id, 
	          cast(@@rowcount as bigint) rows_affected
	', N'@p1 bigint, @p2 bigint, @p3 bigint, @p4 nvarchar (12), @p5 bigint, @p6 nvarchar (5), @p7 bigint, @p8 nvarchar (0), @p9 nvarchar (0), @p10 nvarchar (5), @p11 nvarchar (77), @p12 nvarchar (5), @p13 bigint', @p1=0, @p2=0, @p3=9, @p4='Camera B-13A', @p5=8, @p6='false', @p7=3, @p8='', @p9='', @p10='false', @p11='{"group":"camera","type":"static","exacqId":1234567890,"xPos":123,"yPos":123}', @p12='<nil>', @p13=8"
	write.c:140:tds_put_string converting 431 bytes of "t) rows_affected
	', N'@p1 bigint, @p2 bigint, @p3 bigint, @p4 nvarchar (12), @p5 bigint, @p6 nvarchar (5), @p7 bigint, @p8 nvarchar (0), @p9 nvarchar (0), @p10 nvarchar (5), @p11 nvarchar (77), @p12 nvarchar (5), @p13 bigint', @p1=0, @p2=0, @p3=9, @p4='Camera B-13A', @p5=8, @p6='false', @p7=3, @p8='', @p9='', @p10='false', @p11='{"group":"camera","type":"static","exacqId":1234567890,"xPos":123,"yPos":123}', @p12='<nil>', @p13=8"
	write.c:140:tds_put_string converting 303 bytes of "har (0), @p9 nvarchar (0), @p10 nvarchar (5), @p11 nvarchar (77), @p12 nvarchar (5), @p13 bigint', @p1=0, @p2=0, @p3=9, @p4='Camera B-13A', @p5=8, @p6='false', @p7=3, @p8='', @p9='', @p10='false', @p11='{"group":"camera","type":"static","exacqId":1234567890,"xPos":123,"yPos":123}', @p12='<nil>', @p13=8"
	write.c:140:tds_put_string converting 175 bytes of "era B-13A', @p5=8, @p6='false', @p7=3, @p8='', @p9='', @p10='false', @p11='{"group":"camera","type":"static","exacqId":1234567890,"xPos":123,"yPos":123}', @p12='<nil>', @p13=8"
	write.c:140:tds_put_string converting 47 bytes of "8,"xPos":123,"yPos":123}', @p12='<nil>', @p13=8"
	write.c:168:tds_put_string wrote 1630 bytes
	util.c:156:Changed query state from QUERYING to PENDING
	net.c:741:Sending packet

**Comment by gtczap** [comment]
Also, I am seeing some console errors from go that I did not notice before, such as:

	2015/01/29 11:54:26 unknown dataType false
	2015/01/29 11:54:26 unknown dataType true

I believe these were the types of errors I was seeing before the recent push request for bool support. I'm looking into this one further right now.

**Comment by gtczap** [comment]
My local repo was somehow out of sync with origin/master. I am no longer seeing any of these issues. My apologies - I guess it was my turn to be an idiot for a day :)
