### ISSUE TITLE
Upgrade to FreeTDS 0.95-19 introduced gofreetds issues with nvarchar trailing spaces

### ISSUE THREAD

**Issue by MarkSonghurst** [minus5/gofreetds#16]
Hello.
Platform: CentOS 7 x86_64, Go 1.5.1

I've been reliably using gofreetds with FreeTDS 0.91 (from epel RPM freetds-0.91-12.git0a42888.el7.x86_64) which was recently upgraded to FreeTDS 0.95.19 (freetds-0.95.19-1.el7.x86_64).
Once I performed the update, I cleaned built and installed gofreetds (having also installed the 0.95.19 freetds-devel RPM) but found my Go daemon's database unit tests were failing against both my SQL Server 2014 and 2008 servers, with the same issue.

Upon inspection I could see that trailing spaces were appearing in the data returned from columns of the nvarchar type. So where a returned column was correctly empty (from me pushing up an empty Go string) when using FreeTDS 0.91, when using FreeTDS 0.95 I am now getting a " " (single space) returned. The data within the tables also shows the trailing spaces present.

You can probably guess what I've changed to resolve this :-)
convert_sql_buf.go
/*
			if datatype == XSYBNVARCHAR || datatype == XSYBNCHAR {
				//FIXME - adding len bytes to the end of the buf
				//        realy don't understand why this is necessary
				//        come to this solution by try and error
				l := len(data)
				for i := 0; i < l; i++ {
					data = append(data, byte(0))
				}				
			}
*/

Commenting out that block of code removes the trailing spaces and resolves my issue on 0.95
However, without it, gofreetds will break on 0.91, with the following error being reported:

dbutil.c:86:msgno 8016: "The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 5 ("@nvcFirstname"): Data type 0xE7 has an invalid data length or metadata length."

It appears to me that the FIXME is no longer required in 0.95 but is still required in 0.91
Perhaps the FreeTDS version can be detected at connection time (?) and then the FIXME logic applied as necessary? Or maybe time to draw a line in the sand and say only 0.95 is supported?
Any advice on how to proceed would be welcome. I'm new to GitHub and contributing, so I'm not sure what the etiquette is :-)

My /etc/freetds.conf file is as per initially installed by the FreeTDS RPM, which has no client charset setting in it. Everything in the freetds.log file generated suggests the data is being converted from UTF-8 okay.

**Comment by ianic** [comment]
Could you please try with the latest head. I solved the problem with the trailing spaces in empty string. 
Test are passing for both 0.91 and 0.95 freetds.
However I still don't understand why we need to add spaces on the end of the sting.

Removing that fix, as you did in the patch, works in 0.95 for XSYBNVARCHAR (nvarchar) datatype but sill is needed for XSYBNCHAR (nchar) datatype. 
I didn't manage to get tests passing after applying your pull request.

**Comment by MarkSonghurst** [comment]
Hello. Thank you for spending the time to take a look.

I checked out the latest code but with a fresh build of gofreetds and my daemon the issue still exists.
My DBA reports that for every nvarchar string I push into the database using 0.95, the string is stored double it's original size, with spaces accounting for the additional size.

For example my Go string of "Mark" is stored in the database as "Mark    " (four additional spaces, nvarchar).

We run with ANSI PADDING off. I tested with it ON and OFF in conn.go but it made no difference.

**Comment by ianic** [comment]
Yes, you are right.

Instead of adding spaces on the end of the string we are now setting datalen when pushing stored procedure params. 
I used your code for detecting freetds version. Thanks.

Can you please test with the latest.

**Comment by MarkSonghurst** [comment]
Thank you for the prompt response. I have rebuilt my daemon using your latest changes and will try and test today - unfortunately I'm reliant on my DBA to confirm the fixes and he's stressed out on something else.

**Comment by MarkSonghurst** [comment]
I can confirm that the issue is resolved for me. 
Many thanks for your time on this problem.
