### ISSUE TITLE
Possible resource leak on dead pooled connection

### ISSUE THREAD

**Issue by MarkSonghurst** [minus5/gofreetds#22]
From testing with a SQL Server I could reboot on-demand, I noticed the pool statistics were appearing incorrect. I believe there is a possible resource leak in the ConnPool.addToPool function called by ConnPool.Release

~~~
func (p *ConnPool) addToPool(conn *Conn) {
	p.poolMutex.Lock()
	defer p.poolMutex.Unlock()
	if !conn.isDead() {
		conn.expiresFromPool = time.Now().Add(poolExpiresInterval)
		//release to the top of the pool
		newPool := []*Conn{}
		newPool = append(newPool, conn)
		newPool = append(newPool, p.pool...)
		p.pool = newPool
	}
}
~~~

If conn.isDead() is true, then I the connection is not being closed and p.connCount is not being decremented. There are some FreeTDS calls in Conn.close() which I suspect if not called, could result in a resource leak.

**Comment by MarkSonghurst** [comment]
The following Pull Request (off my fork) proposes a solution to the resource leak:
https://github.com/MarkSonghurst/gofreetds/pull/1

**Comment by ianic** [comment]
Thanks.
I picked that from your fork.
