### ISSUE TITLE
varchar(max) panics on makeslice: len out of range

### ISSUE THREAD

**Issue by NoICE** [minus5/gofreetds#26]
Hello,

I love this library. But I have a little issue with varchar(max). When I try to execute a statement on a table that has varchar(MAX) defined column, gofreetds crashes with this stacktrace:

```
panic: runtime error: makeslice: len out of range

goroutine 35 [running]:
github.com/minus5/gofreetds.(*Conn).fetchResults(0xc8200dc0d0, 0x0, 0x0, 0x0, 0x0, 0x0)
        [...]/Godeps/_workspace/src/github.com/minus5/gofreetds/fetch.go:50 +0x6a5
github.com/minus5/gofreetds.(*Conn).exec(0xc8200dc0d0, 0xc82017a000, 0x597, 0x0, 0x0, 0x0, 0x0, 0x0)
        [...]/Godeps/_workspace/src/github.com/minus5/gofreetds/conn.go:276 +0x1be
github.com/minus5/gofreetds.(*Conn).Exec(0xc8200dc0d0, 0xc82017a000, 0x597, 0x0, 0x0, 0x0, 0x0, 0x0)
        [...]/Godeps/_workspace/src/github.com/minus5/gofreetds/conn.go:214 +0x6e
github.com/minus5/gofreetds.(*Conn).ExecuteSql(0xc8200dc0d0, 0xc820168000, 0x2ce, 0xc8200e2200, 0x10, 0x10, 0x0, 0x0, 0x0, 0x0, ...)
        [...]/Godeps/_workspace/src/github.com/minus5/gofreetds/executesql.go:30 +0x679
// ...
```

Which is caused by the last line of this:

```go
// fetch.go line 
			col := &columns[i]
// ...
			col.size = int(size)
// ...
			col.buffer = make([]byte, size+1)
```

Why is there that "+1" and why we need to preallocate the memory before the data are read from the connection? I don't know how freetds works, but doesn't it know the data size in advance?
I tried to avoid this issue by not using varchar(max), but now I have to use database which I cannot change.

Tested on latest rev. (0594db19), go 1.5.1 darwin/amd64.

Maybe it has something in common with #25 ?

**Comment by ianic** [comment]
Thanks, NoICE.

For varchar(max) this line:
```
size := C.dbcollen(conn.dbproc, no)
```
returns 2147483647. Adding one to int32 results in negative number, and the slice allocation panics.

Fixing this in: https://github.com/minus5/gofreetds/commit/c14e66f7a5f44595c1eeadcf872f29b711e895ff

**Comment by NoICE** [comment]
Hello and thanks! But isn't limiting to 8k a little too much restraining? I mean, there are many people who have texts in their databases. I did a query for max length of data column present in a table which uses varchar(max) and the largest one was 32k.

I'm currently exploring the option of use dbdatlen() (http://www.freetds.org/reference/a00341.html#gae666d141533126babb0235af21bdca0f) freetds function, but freetds is new to me and I don't know if it returns this thing different for each row and if I can all dbbind for each row...
