### ISSUE TITLE
How to connect to DB not on default port?

### ISSUE THREAD

**Issue by isparks** [minus5/gofreetds#3]
FreeTDS allows setting of TDSVER and TDSPORT environment variables but according to TDSDUMP logs setting these has no effect on gofreetds and there is also no way of changing the port or TDS version in code that I can see.

I want to connect to a SQL Server 2008 R2 (TDSVER 7.2) Database on port 1435 (not 1433)

Is it possible?

**Comment by sdhjl2000** [comment]
the password is longer than 30,i set TDSVER=7.0 and test with tsql command  is ok,but don't work with code. any suggestion?
