### ISSUE TITLE
Executing stored procedure doesn't return data

### ISSUE THREAD

**Issue by ilijamt** [minus5/gofreetds#34]
I have the following code

```
rst, err := conn.ExecSp("sp_help", "ABS")
if err != nil {
	panic(err)
}


if rst.NextResult() {
    for rst.Next() {
	var v1, v2, v3, v4, v5, v6 string
	rst.Scan(&v1, &v2, &v3, &v4, &v5, &v6)
	fmt.Printf("%s, %s, %s, %s, %s, %s", v1, v2, v3, v4, v5, v6)
    }
}

```
Running **exec sp_help ABS;** in the management studio work it returns data, but whenever I do this it never returns data.

Also running **sp_fkeys** crashes with an error 

```
Msg 8009, Level 16, State 1
Server 'EGL-IRV-ASP07', Line 1
	The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 1 ("@pktable_name"): Data type 0x00 is unknown.
```

Executing regular SQLs work and data is returned, and all the stored procedure work if executed from the Management Studio.

**Comment by MarkSonghurst** [comment]
Be aware that the names of the variables which are used to get the result sets in the call to Scan must be identical (including case) as the column names in the results sets.

Another gotcha is that gofreetds internally performs a CamelCase conversion of each variable name, so if you have columns which are using uppercase, you might struggle to get them back as results. 

For example: When using a variable which maps to a column called IPAddress I cannot get back the result as gofreetds will internally convert it's name to IpAddress which no longer matches the column name.
If my DBA renames the column to IpAddress then it will work.

I suspect your columns are not called v1, v2, etc so you need to rename those variables to case-sensitive match the column names and ensure you column names are CamelCase.

Hope that helps.

**Comment by ianic** [comment]
Check the error that rst.Scan is returning.
In this case error is something like: "More dest values 6 than src values 4."

sp_help is returning many resultsets. First has 4 columns: 
Name, Owner, Type, Created_datetime   

You are scanning first row of this resultset into 6 strings.
Try something like this:
```
func TestSpHelp(t *testing.T) {
	conn := ConnectToTestDb(t)
	rst, err := conn.ExecSp("sp_help", "authors")
	assert.Nil(t, err)

	if rst.NextResult() {
		for rst.Next() {
			var v1, v2, v3 string
			var t1 time.Time
			err := rst.Scan(&v1, &v2, &v3, &t1)
			assert.Nil(t, err)
			fmt.Printf("%s, %s, %s, %v", v1, v2, v3, t1)
		}
	}
}
```
This is working example on test db. That db has table named 'authors'.

If you want to scan into struct:
```
func TestSpHelpStructScan(t *testing.T) {
	conn := ConnectToTestDb(t)
	rst, err := conn.ExecSp("sp_help", "authors")
	assert.Nil(t, err)

	data := struct {
		Name            string
		Owner           string
		Type            string
		CreatedDatetime time.Time
	}{}

	if rst.NextResult() {
		for rst.Next() {
			err := rst.Scan(&data)
			assert.Nil(t, err)
			fmt.Printf("struct scan: %#v\n", data)
		}
	}
}
```

**Comment by ianic** [comment]
My databases are built to fit with Rails. So I'm following Rails convention so it is column_name not ColumnName. 
When building gofreetds I wan't to scan column_name into ColumnName so I build a little help for that.

This code is finding struct filed for database column:
```
		f := s.FieldByName(camelize(col.Name))
```
What is camelize doing is best described in test: https://github.com/minus5/gofreetds/blob/master/camelize_test.go

There is no forcing of CamelCase.
Column name IPAddress should be scanned into IPAddress struct field.
Column ip_address is looking for IpAddress struct filed.

**Comment by caledhwa** [comment]
Awesome. Looks like I was just sucked into the disinformation of the reported issue. Ignore my comments. Good stuff Igor

**Comment by MarkSonghurst** [comment]
@ianic Apologies, my IPAddress example is clearly wrong.
However, wouldn't the camelize call cause a problem if you are not using Rails, but are using underscores or hyphens in your column names? Perhaps SQL Server forbids that?

**Comment by ianic** [comment]
SQL Server accepts nearly anything in column name, if enclosed in [], for example:
```
create table tbl (
  id int,
  [some-filed:name] int
)
```
Current gofreetds will expect SomeFieldName struct field in this case.


I know that current solution does a little magic. That should be better documented.
There will be probably cases especially when working with legacy databases where this will not fit. One solution is to make a view or stored procedure to do some column name transformation. I know that this is not always doable. Especially in the case when you are not allowed to change db schema.
Long term solution to fit all db schemas will be to develop struct tags for describing column names. 
For example:

```
type Result struct {
   IPAddress `sql:"request_ip"`
   ...
}
```

**Comment by ilijamt** [comment]
@ianic I can't really change the names, as I need only sp_help, sp_columns, sp_fkeys and they are system stored procedures.

I tried executing them without ExecSp and I've managed to get sp_columns and sp_fkeys to work, but not sp_help for some reason.

```
type FOREIGN_KEYS struct {
	PKTABLE_QUALIFIER string
	PKTABLE_OWNER string
	PKTABLE_NAME string
	PKCOLUMN_NAME string
	FKTABLE_QUALIFIER string
	FKTABLE_OWNER string
	FKTABLE_NAME string
	FKCOLUMN_NAME string
	KEY_SEQ string
	UPDATE_RULE string
	DELETE_RULE string
	FK_NAME string
	PK_NAME string
	DEFERRABILITY string
}

type COLUMN struct {
	TABLE_QUALIFIER string
	TABLE_OWNER string
	TABLE_NAME string
	COLUMN_NAME string
	DATA_TYPE string
	TYPE_NAME string
	PRECISION string
	LENGTH string
	SCALE string
	RADIX string
	NULLABLE string
	REMARKS string
	COLUMN_DEF string
	SQL_DATA_TYPE string
	SQL_DATETIME_SUB string
	CHAR_OCTET_LENGTH string
	ORDINAL_POSITION string
	IS_NULLABLE string
	SS_DATA_TYPE string
}

type TableStructure struct {
   TableName string
   Columns []COLUMN
   ForeignKeys []FOREIGN_KEYS
}

type DbStructure struct {
   DbName string
   Tables []TableStructure
}
```

This is basically the structures that I need to fill the data with.

**Comment by ianic** [comment]
@ilijamt please look at the  example of using sp_help:
https://github.com/minus5/gofreetds/blob/master/example/sp_help/main.go
You can use this as starting point. I processed just first two resultset but you'll get the idea.

If you are doing Scan on resultset check returned errors.

One problem in the above struct is that you can't scan nullable columns into non nillable type. For example: 'REMARKS string' should be defined as 'REMARKS *string' because in resultset that is nullable column. In this case Scan should return error: 'unsupported driver -> Scan pair: <nil> -> *string'
