### ISSUE TITLE
Support for sql server 2000?

### ISSUE THREAD

**Issue by huaguoping** [minus5/gofreetds#46]
Could I use this driver to connect sql server 2000?When I did this, I got an error:

Cannot connect:  dbopen error
Msg 20002, Level 9
Adaptive Server connection failed (my sql server host)

I used the correct connect information, host, user name, password, database name...
but it dose not work, could anyone help me? :(

**Comment by MarkSonghurst** [comment]
I have not tried SQL Server 2000, but you might need to modify your /etc/freetds.conf file to set the TDS Version.
But first, have you tried connecting using the FreeTDS tsql connection testing program?
man tsql

That should help you figure out any connection issues without needing to write code.

**Comment by hongjinlin** [comment]
In my case,it works!
![image](https://user-images.githubusercontent.com/11484312/50128548-6dbb4580-02b0-11e9-9d03-580a5e5f1635.png)

**Comment by aleskandro** [comment]
Compatibility Mode set to Sybase did the trick!

```
fmt.Sprintf("user=%s;pwd=;database=%s;host=%s;port=%d; Compatibility Mode=Sybase",
		conf.DBMSUser, conf.DBMSDBName, conf.DBMSHost, conf.DBMSPort)

```

**Comment by WK-LLP** [comment]
> it also works for me.
