### ISSUE TITLE
Dead link under Sybase Compatibility Mode 

### ISSUE THREAD

**Issue by andyedison** [minus5/gofreetds#52]
Hello,

I wanted to let you know that the link under this section in the readme [Sybase Compatibility Mode](https://github.com/minus5/gofreetds#sybase-compatibility-mode) is dead.

here is the link in question
[http://2tbsp.com/articles/2012/06/08/connect-ms-sql-server-and-sybase-ase-mac-os-x-and-linux-unixodbc-and-freetds](http://2tbsp.com/articles/2012/06/08/connect-ms-sql-server-and-sybase-ase-mac-os-x-and-linux-unixodbc-and-freetds)

Thanks.

**Comment by patko** [comment]
Thankfully there is a [copy of this article](http://web.archive.org/web/20160325095720/http://2tbsp.com/articles/2012/06/08/connect-ms-sql-server-and-sybase-ase-mac-os-x-and-linux-unixodbc-and-freetds) in Internet Archive.

**Comment by patko** [comment]
I committed updated document.
