### ISSUE TITLE
README Connection Pool Incorrect

### ISSUE THREAD

**Issue by isparks** [minus5/gofreetds#6]
Hi, regarding connection pooling the Readme says:

//create connection pool (for max. 100 connections)
pool, err := freetds.NewConnPool("user=ianic;pwd=ianic;database=pubs;host=iow", 100)

But NewConnPool() takes only a connection string, not a pool size.

**Comment by ianic** [comment]
Fixed in 20a44d68504165308476faa57eb242648e212d04.
