### ISSUE TITLE
Driver corrupts byte slices

### ISSUE THREAD

**Issue by mromaszewicz** [minus5/gofreetds#60]
I've got a couple of issues reading and writing []byte arrays to MSSQL via the gofreetds driver. I'm attaching a small example which truncates data. When I write []byte{1, 2, 3, 4, 5}, reading it back gets []byte{1, 2, 3, 4}.

What I have not been able to reproduce in this small program is that sometimes, when reading back the result set, the byte buffer returned is huge, with only the first few items populated. In this case, []byte{1, 2, 3, 4, 5, 0...]. It's zero padded up to a length of 64512, which smells awfully close to a 64k read buffer size - so maybe we're getting back some whole buffer instead of the bytes actually read?

In any case, I always get one of the two results - the truncated version missing the last byte, or the huge buffer which contains the desired bytes at the beginning.

[main.txt](https://github.com/minus5/gofreetds/files/1361218/main.txt)

**Comment by ianic** [comment]
@mromaszewicz Please try with the latest commit.
