### ISSUE TITLE
Unit Tests depend on a table created in TestCreateTable

### ISSUE THREAD

**Issue by carebdayrvis** [minus5/gofreetds#62]
When running the unit tests against a freshly setup DB, the tests will fail at `conn_sp_test:318`, since the TestCreateTable hasn't been run. The solution would be to have table created in some sort of setup function or something. I might be able to submit a PR for this, but I wanted to open an issue in case I am unable to.

**Comment by MarkSonghurst** [comment]
Good spot! 
I've not noticed this occurring myself, but I agree. Chances are I'm not regularly running against a fresh DB.
I think adding a `func TestMain(m *testing.M)` to perform pre-test setup (I guess all of the test case TestCreateTable) is one possible answer.
