### ISSUE TITLE
Cross compilation failed？

### ISSUE THREAD

**Issue by hjzCy** [minus5/gofreetds#72]
VSCode mac -> windows

```shell
➜  Sendsms CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build main.go
# github.com/minus5/gofreetds
../../../../go/pkg/mod/github.com/minus5/gofreetds@v0.0.0-20190219163700-c92a62efdcd5/conn_pool.go:33:19: undefined: Conn
../../../../go/pkg/mod/github.com/minus5/gofreetds@v0.0.0-20190219163700-c92a62efdcd5/params_cache.go:8:22: undefined: spParam
```

**Comment by ianic** [comment]
We are depending here on freetds package. Which is C library, so we can't build project with cgo disabled.
That probably makes cross compiling impossible or at least much harder.

**Comment by hjzCy** [comment]
Can I compile on a Windows system?

**Comment by ianic** [comment]
Newer tried. But I don't know of any show stopper. 
Both Go and [freetds](https://www.freetds.org/userguide/osissues.htm#WINDOWS) are available on that platform.

**Comment by shandets** [comment]
@hjzCy Did you get this error when you used "github.com/jmoiron/sqlx" or "database/sql" or something else?
