### ISSUE TITLE
Ambiguous error message "dbopen error"

### ISSUE THREAD

**Issue by dcerjan** [minus5/gofreetds#9]
#### Steps to reproduce:
* try to connect to database with user that does not exist

#### Expected result: 
* eg. 'dbopen error: auth failure' or similar

#### Actual result: 
* 'dbopen error'

#### Note:
* using freetdsdump (http://www.freetds.org/userguide/logging.htm) the correct error message is visible

**Comment by ianic** [comment]
Good point, fixed in 109b8c94de97c4644026f2b59c13187d2adcd948.
